services:
  qdrant:
    image: qdrant/qdrant:v1.17.1
    container_name: rag-db
    networks:
      - net
    volumes:
      - ./database-qdrant:/qdrant/storage
  redis:
    image: redis:7.4.0
    container_name: rag-redis
    networks:
      - net
    volumes:
      - ./database-redis:/data
  server:
    build:
      context: ./backend
      args:
        HF_TOKEN: ${HF_TOKEN}
        EMBEDDING_MODEL: intfloat/multilingual-e5-large
        EMBEDDING_DIMENSION: 1024
    image: rag-server:latest
    container_name: rag-server
    volumes:
      - ./data:/app/data
    depends_on:
      - qdrant
      - redis
    networks:
      - net
  frontend:
    build:
      context: ./frontend
    image: rag-frontend:latest
    container_name: rag-frontend
    ports:
      - "3000:80"
    networks:
      - net

networks:
  net:
    driver: bridge